global:
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: "eleanor-api"
    metrics_path: /metrics
    static_configs:
      - targets: ["eleanor:8000"]

  - job_name: "opa"
    metrics_path: /metrics
    static_configs:
      - targets: ["opa:8181"]

  - job_name: "dependency-exporter"
    metrics_path: /metrics
    static_configs:
      - targets: ["dependency-exporter:9105"]
